using Grafitist.Models.Campaign;
using Grafitist.Models.Cart;
using Grafitist.Models.CompanyInfo;
using Grafitist.Models.Order;
using Grafitist.Models.Payment;
using Grafitist.Models.Product;
using Grafitist.Models.Stock;
using Grafitist.Models.User;
using Microsoft.EntityFrameworkCore;

namespace Grafitist.Connection;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> obj) : base(obj)
    { }

    public DbSet<CampaignModel>? Campaigns { get; set; }

    public DbSet<CartModel>? Carts { get; set; }
    public DbSet<CartLineModel>? CartLines { get; set; }

    public DbSet<CompanyInfoModel>? CompanyInfos { get; set; }

    public DbSet<OrderModel>? Orders { get; set; }
    public DbSet<OrderLineModel>? OrderLines { get; set; }

    public DbSet<PaymentModel>? Payments { get; set; }

    public DbSet<ColorModel>? Colors { get; set; }
    public DbSet<VariantModel>? Variants { get; set; }
    public DbSet<MaterialModel>? Materials { get; set; }
    public DbSet<CategoryModel>? Categories { get; set; }
    public DbSet<ImageModel>? Images { get; set; }
    public DbSet<ProductModel>? Products { get; set; }

    public DbSet<StockModel>? Stocks { get; set; }

    public DbSet<UserModel>? Users { get; set; }
    public DbSet<AddressModel>? Addresses { get; set; }
    public DbSet<CityModel>? Cities { get; set; }
    public DbSet<DistrictModel>? Districts { get; set; }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<CityModel>().HasData(CreateCityModels());
        modelBuilder.Entity<DistrictModel>().HasData(CreateDistrictModels());
        modelBuilder.Entity<UserModel>().HasData(CreateAdminUser());
        modelBuilder.Entity<CompanyInfoModel>().HasData(CreateCompanyInfo());
    }

    #region AdminUser
    private UserModel CreateAdminUser()
    {
        return new UserModel
        {
            Id = Guid.NewGuid(),
            Type = Misc.Enums.UserType.Admin,
            Email = "okanerkan@hotmail.com",
            Name = "Okan",
            Surname = "Erkan",
            Password = Misc.AesEncryption.Encrypt("12345678")
        };
    }
    #endregion

    #region Address Data
    private IEnumerable<CityModel> CreateCityModels()
    {
        var cityModels = new List<CityModel>();
        cityModels.Add(CreateCityModel(1, "Adana"));
        cityModels.Add(CreateCityModel(2, "Adıyaman"));
        cityModels.Add(CreateCityModel(3, "Afyonkarahisar"));
        cityModels.Add(CreateCityModel(4, "Ağrı"));
        cityModels.Add(CreateCityModel(5, "Aksaray"));
        cityModels.Add(CreateCityModel(6, "Amasya"));
        cityModels.Add(CreateCityModel(7, "Ankara"));
        cityModels.Add(CreateCityModel(8, "Antalya"));
        cityModels.Add(CreateCityModel(9, "Ardahan"));
        cityModels.Add(CreateCityModel(10, "Artvin"));
        cityModels.Add(CreateCityModel(11, "Aydın"));
        cityModels.Add(CreateCityModel(12, "Balıkesir"));
        cityModels.Add(CreateCityModel(13, "Bartın"));
        cityModels.Add(CreateCityModel(14, "Batman"));
        cityModels.Add(CreateCityModel(15, "Bayburt"));
        cityModels.Add(CreateCityModel(16, "Bilecik"));
        cityModels.Add(CreateCityModel(17, "Bingöl"));
        cityModels.Add(CreateCityModel(18, "Bitlis"));
        cityModels.Add(CreateCityModel(19, "Bolu"));
        cityModels.Add(CreateCityModel(20, "Burdur"));
        cityModels.Add(CreateCityModel(21, "Bursa"));
        cityModels.Add(CreateCityModel(22, "Çanakkale"));
        cityModels.Add(CreateCityModel(23, "Çankırı"));
        cityModels.Add(CreateCityModel(24, "Çorum"));
        cityModels.Add(CreateCityModel(25, "Denizli"));
        cityModels.Add(CreateCityModel(26, "Diyarbakır"));
        cityModels.Add(CreateCityModel(27, "Düzce"));
        cityModels.Add(CreateCityModel(28, "Edirne"));
        cityModels.Add(CreateCityModel(29, "Elazığ"));
        cityModels.Add(CreateCityModel(30, "Erzincan"));
        cityModels.Add(CreateCityModel(31, "Erzurum"));
        cityModels.Add(CreateCityModel(32, "Eskişehir"));
        cityModels.Add(CreateCityModel(33, "Gaziantep"));
        cityModels.Add(CreateCityModel(34, "Giresun"));
        cityModels.Add(CreateCityModel(35, "Gümüşhane"));
        cityModels.Add(CreateCityModel(36, "Hakkari"));
        cityModels.Add(CreateCityModel(37, "Hatay"));
        cityModels.Add(CreateCityModel(38, "Iğdır"));
        cityModels.Add(CreateCityModel(39, "Isparta"));
        cityModels.Add(CreateCityModel(40, "İstanbul"));
        cityModels.Add(CreateCityModel(41, "İzmir"));
        cityModels.Add(CreateCityModel(42, "Kahramanmaraş"));
        cityModels.Add(CreateCityModel(43, "Karabük"));
        cityModels.Add(CreateCityModel(44, "Karaman"));
        cityModels.Add(CreateCityModel(45, "Kars"));
        cityModels.Add(CreateCityModel(46, "Kastamonu"));
        cityModels.Add(CreateCityModel(47, "Kayseri"));
        cityModels.Add(CreateCityModel(48, "Kilis"));
        cityModels.Add(CreateCityModel(49, "Kırıkkale"));
        cityModels.Add(CreateCityModel(50, "Kırklareli"));
        cityModels.Add(CreateCityModel(51, "Kırşehir"));
        cityModels.Add(CreateCityModel(52, "Kocaeli"));
        cityModels.Add(CreateCityModel(53, "Konya"));
        cityModels.Add(CreateCityModel(54, "Kütahya"));
        cityModels.Add(CreateCityModel(55, "Malatya"));
        cityModels.Add(CreateCityModel(56, "Manisa"));
        cityModels.Add(CreateCityModel(57, "Mardin"));
        cityModels.Add(CreateCityModel(58, "Mersin"));
        cityModels.Add(CreateCityModel(59, "Muğla"));
        cityModels.Add(CreateCityModel(60, "Muş"));
        cityModels.Add(CreateCityModel(61, "Nevşehir"));
        cityModels.Add(CreateCityModel(62, "Niğde"));
        cityModels.Add(CreateCityModel(63, "Ordu"));
        cityModels.Add(CreateCityModel(64, "Osmaniye"));
        cityModels.Add(CreateCityModel(65, "Rize"));
        cityModels.Add(CreateCityModel(66, "Sakarya"));
        cityModels.Add(CreateCityModel(67, "Samsun"));
        cityModels.Add(CreateCityModel(68, "Şanlıurfa"));
        cityModels.Add(CreateCityModel(69, "Siirt"));
        cityModels.Add(CreateCityModel(70, "Sinop"));
        cityModels.Add(CreateCityModel(71, "Şırnak"));
        cityModels.Add(CreateCityModel(72, "Sivas"));
        cityModels.Add(CreateCityModel(73, "Tekirdağ"));
        cityModels.Add(CreateCityModel(74, "Tokat"));
        cityModels.Add(CreateCityModel(75, "Trabzon"));
        cityModels.Add(CreateCityModel(76, "Tunceli"));
        cityModels.Add(CreateCityModel(77, "Uşak"));
        cityModels.Add(CreateCityModel(78, "Van"));
        cityModels.Add(CreateCityModel(79, "Yalova"));
        cityModels.Add(CreateCityModel(80, "Yozgat"));
        cityModels.Add(CreateCityModel(81, "Zonguldak"));
        return cityModels;
    }

    private CityModel CreateCityModel(int id, string city)
    {
        return new CityModel
        {
            Id = id,
            Name = city
        };
    }

    private IEnumerable<DistrictModel> CreateDistrictModels()
    {
        var districtModels = new List<DistrictModel>();
        districtModels.Add(CreateDistrictModel(1, "Aladağ", 1));
        districtModels.Add(CreateDistrictModel(2, "Ceyhan", 1));
        districtModels.Add(CreateDistrictModel(3, "Çukurova", 1));
        districtModels.Add(CreateDistrictModel(4, "Feke", 1));
        districtModels.Add(CreateDistrictModel(5, "İmamoğlu", 1));
        districtModels.Add(CreateDistrictModel(6, "Karaisalı", 1));
        districtModels.Add(CreateDistrictModel(7, "Karataş", 1));
        districtModels.Add(CreateDistrictModel(8, "Kozan", 1));
        districtModels.Add(CreateDistrictModel(9, "Pozantı", 1));
        districtModels.Add(CreateDistrictModel(10, "Saimbeyli", 1));
        districtModels.Add(CreateDistrictModel(11, "Sarıçam", 1));
        districtModels.Add(CreateDistrictModel(12, "Seyhan", 1));
        districtModels.Add(CreateDistrictModel(13, "Tufanbeyli", 1));
        districtModels.Add(CreateDistrictModel(14, "Yumurtalık", 1));
        districtModels.Add(CreateDistrictModel(15, "Yüreğir", 1));
        districtModels.Add(CreateDistrictModel(16, "Besni", 2));
        districtModels.Add(CreateDistrictModel(17, "Çelikhan", 2));
        districtModels.Add(CreateDistrictModel(18, "Gerger", 2));
        districtModels.Add(CreateDistrictModel(19, "Gölbaşı", 2));
        districtModels.Add(CreateDistrictModel(20, "Kahta", 2));
        districtModels.Add(CreateDistrictModel(21, "Merkez", 2));
        districtModels.Add(CreateDistrictModel(22, "Samsat", 2));
        districtModels.Add(CreateDistrictModel(23, "Sincik", 2));
        districtModels.Add(CreateDistrictModel(24, "Tut", 2));
        districtModels.Add(CreateDistrictModel(25, "Başmakçı", 3));
        districtModels.Add(CreateDistrictModel(26, "Bayat", 3));
        districtModels.Add(CreateDistrictModel(27, "Bolvadin", 3));
        districtModels.Add(CreateDistrictModel(28, "Çay", 3));
        districtModels.Add(CreateDistrictModel(29, "Çobanlar", 3));
        districtModels.Add(CreateDistrictModel(30, "Dazkırı", 3));
        districtModels.Add(CreateDistrictModel(31, "Dinar", 3));
        districtModels.Add(CreateDistrictModel(32, "Emirdağ", 3));
        districtModels.Add(CreateDistrictModel(33, "Evciler", 3));
        districtModels.Add(CreateDistrictModel(34, "Hocalar", 3));
        districtModels.Add(CreateDistrictModel(35, "İhsaniye", 3));
        districtModels.Add(CreateDistrictModel(36, "İscehisar", 3));
        districtModels.Add(CreateDistrictModel(37, "Kızılören", 3));
        districtModels.Add(CreateDistrictModel(38, "Merkez", 3));
        districtModels.Add(CreateDistrictModel(39, "Sandıklı", 3));
        districtModels.Add(CreateDistrictModel(40, "Sinanpaşa", 3));
        districtModels.Add(CreateDistrictModel(41, "Şuhut", 3));
        districtModels.Add(CreateDistrictModel(42, "Sultandağı", 3));
        districtModels.Add(CreateDistrictModel(43, "Diyadin", 4));
        districtModels.Add(CreateDistrictModel(44, "Doğubayazıt", 4));
        districtModels.Add(CreateDistrictModel(45, "Eleşkirt", 4));
        districtModels.Add(CreateDistrictModel(46, "Hamur", 4));
        districtModels.Add(CreateDistrictModel(47, "Merkez", 4));
        districtModels.Add(CreateDistrictModel(48, "Patnos", 4));
        districtModels.Add(CreateDistrictModel(49, "Taşlıçay", 4));
        districtModels.Add(CreateDistrictModel(50, "Tutak", 4));
        districtModels.Add(CreateDistrictModel(51, "Ağaçören", 5));
        districtModels.Add(CreateDistrictModel(52, "Eskil", 5));
        districtModels.Add(CreateDistrictModel(53, "Gülağaç", 5));
        districtModels.Add(CreateDistrictModel(54, "Güzelyurt", 5));
        districtModels.Add(CreateDistrictModel(55, "Merkez", 5));
        districtModels.Add(CreateDistrictModel(56, "Ortaköy", 5));
        districtModels.Add(CreateDistrictModel(57, "Sarıyahşi", 5));
        districtModels.Add(CreateDistrictModel(58, "Sultanhanı", 5));
        districtModels.Add(CreateDistrictModel(59, "Göynücek", 6));
        districtModels.Add(CreateDistrictModel(60, "Gümüşhacıköy", 6));
        districtModels.Add(CreateDistrictModel(61, "Hamamözü", 6));
        districtModels.Add(CreateDistrictModel(62, "Merkez", 6));
        districtModels.Add(CreateDistrictModel(63, "Merzifon", 6));
        districtModels.Add(CreateDistrictModel(64, "Suluova", 6));
        districtModels.Add(CreateDistrictModel(65, "Taşova", 6));
        districtModels.Add(CreateDistrictModel(66, "Akyurt", 7));
        districtModels.Add(CreateDistrictModel(67, "Altındağ", 7));
        districtModels.Add(CreateDistrictModel(68, "Ayaş", 7));
        districtModels.Add(CreateDistrictModel(69, "Bala", 7));
        districtModels.Add(CreateDistrictModel(70, "Beypazarı", 7));
        districtModels.Add(CreateDistrictModel(71, "Çamlıdere", 7));
        districtModels.Add(CreateDistrictModel(72, "Çankaya", 7));
        districtModels.Add(CreateDistrictModel(73, "Çubuk", 7));
        districtModels.Add(CreateDistrictModel(74, "Elmadağ", 7));
        districtModels.Add(CreateDistrictModel(75, "Etimesgut", 7));
        districtModels.Add(CreateDistrictModel(76, "Evren", 7));
        districtModels.Add(CreateDistrictModel(77, "Gölbaşı", 7));
        districtModels.Add(CreateDistrictModel(78, "Güdül", 7));
        districtModels.Add(CreateDistrictModel(79, "Haymana", 7));
        districtModels.Add(CreateDistrictModel(80, "Kahramankazan", 7));
        districtModels.Add(CreateDistrictModel(81, "Kalecik", 7));
        districtModels.Add(CreateDistrictModel(82, "Keçiören", 7));
        districtModels.Add(CreateDistrictModel(83, "Kızılcahamam", 7));
        districtModels.Add(CreateDistrictModel(84, "Mamak", 7));
        districtModels.Add(CreateDistrictModel(85, "Nallıhan", 7));
        districtModels.Add(CreateDistrictModel(86, "Polatlı", 7));
        districtModels.Add(CreateDistrictModel(87, "Pursaklar", 7));
        districtModels.Add(CreateDistrictModel(88, "Şereflikoçhisar", 7));
        districtModels.Add(CreateDistrictModel(89, "Sincan", 7));
        districtModels.Add(CreateDistrictModel(90, "Yenimahalle", 7));
        districtModels.Add(CreateDistrictModel(91, "Akseki", 8));
        districtModels.Add(CreateDistrictModel(92, "Aksu", 8));
        districtModels.Add(CreateDistrictModel(93, "Alanya", 8));
        districtModels.Add(CreateDistrictModel(94, "Demre", 8));
        districtModels.Add(CreateDistrictModel(95, "Döşemealtı", 8));
        districtModels.Add(CreateDistrictModel(96, "Elmalı", 8));
        districtModels.Add(CreateDistrictModel(97, "Finike", 8));
        districtModels.Add(CreateDistrictModel(98, "Gazipaşa", 8));
        districtModels.Add(CreateDistrictModel(99, "Gündoğmuş", 8));
        districtModels.Add(CreateDistrictModel(100, "İbradı", 8));
        districtModels.Add(CreateDistrictModel(101, "Kaş", 8));
        districtModels.Add(CreateDistrictModel(102, "Kemer", 8));
        districtModels.Add(CreateDistrictModel(103, "Kepez", 8));
        districtModels.Add(CreateDistrictModel(104, "Konyaaltı", 8));
        districtModels.Add(CreateDistrictModel(105, "Korkuteli", 8));
        districtModels.Add(CreateDistrictModel(106, "Kumluca", 8));
        districtModels.Add(CreateDistrictModel(107, "Manavgat", 8));
        districtModels.Add(CreateDistrictModel(108, "Muratpaşa", 8));
        districtModels.Add(CreateDistrictModel(109, "Serik", 8));
        districtModels.Add(CreateDistrictModel(110, "Çıldır", 9));
        districtModels.Add(CreateDistrictModel(111, "Damal", 9));
        districtModels.Add(CreateDistrictModel(112, "Göle", 9));
        districtModels.Add(CreateDistrictModel(113, "Hanak", 9));
        districtModels.Add(CreateDistrictModel(114, "Merkez", 9));
        districtModels.Add(CreateDistrictModel(115, "Posof", 9));
        districtModels.Add(CreateDistrictModel(116, "Ardanuç", 10));
        districtModels.Add(CreateDistrictModel(117, "Arhavi", 10));
        districtModels.Add(CreateDistrictModel(118, "Borçka", 10));
        districtModels.Add(CreateDistrictModel(119, "Hopa", 10));
        districtModels.Add(CreateDistrictModel(120, "Kemalpaşa", 10));
        districtModels.Add(CreateDistrictModel(121, "Merkez", 10));
        districtModels.Add(CreateDistrictModel(122, "Murgul", 10));
        districtModels.Add(CreateDistrictModel(123, "Şavşat", 10));
        districtModels.Add(CreateDistrictModel(124, "Yusufeli", 10));
        districtModels.Add(CreateDistrictModel(125, "Bozdoğan", 11));
        districtModels.Add(CreateDistrictModel(126, "Buharkent", 11));
        districtModels.Add(CreateDistrictModel(127, "Çine", 11));
        districtModels.Add(CreateDistrictModel(128, "Didim", 11));
        districtModels.Add(CreateDistrictModel(129, "Efeler", 11));
        districtModels.Add(CreateDistrictModel(130, "Germencik", 11));
        districtModels.Add(CreateDistrictModel(131, "İncirliova", 11));
        districtModels.Add(CreateDistrictModel(132, "Karacasu", 11));
        districtModels.Add(CreateDistrictModel(133, "Karpuzlu", 11));
        districtModels.Add(CreateDistrictModel(134, "Koçarlı", 11));
        districtModels.Add(CreateDistrictModel(135, "Köşk", 11));
        districtModels.Add(CreateDistrictModel(136, "Kuşadası", 11));
        districtModels.Add(CreateDistrictModel(137, "Kuyucak", 11));
        districtModels.Add(CreateDistrictModel(138, "Nazilli", 11));
        districtModels.Add(CreateDistrictModel(139, "Söke", 11));
        districtModels.Add(CreateDistrictModel(140, "Sultanhisar", 11));
        districtModels.Add(CreateDistrictModel(141, "Yenipazar", 11));
        districtModels.Add(CreateDistrictModel(142, "Altıeylül", 12));
        districtModels.Add(CreateDistrictModel(143, "Ayvalık", 12));
        districtModels.Add(CreateDistrictModel(144, "Balya", 12));
        districtModels.Add(CreateDistrictModel(145, "Bandırma", 12));
        districtModels.Add(CreateDistrictModel(146, "Bigadiç", 12));
        districtModels.Add(CreateDistrictModel(147, "Burhaniye", 12));
        districtModels.Add(CreateDistrictModel(148, "Dursunbey", 12));
        districtModels.Add(CreateDistrictModel(149, "Edremit", 12));
        districtModels.Add(CreateDistrictModel(150, "Erdek", 12));
        districtModels.Add(CreateDistrictModel(151, "Gömeç", 12));
        districtModels.Add(CreateDistrictModel(152, "Gönen", 12));
        districtModels.Add(CreateDistrictModel(153, "Havran", 12));
        districtModels.Add(CreateDistrictModel(154, "İvrindi", 12));
        districtModels.Add(CreateDistrictModel(155, "Karesi", 12));
        districtModels.Add(CreateDistrictModel(156, "Kepsut", 12));
        districtModels.Add(CreateDistrictModel(157, "Manyas", 12));
        districtModels.Add(CreateDistrictModel(158, "Marmara", 12));
        districtModels.Add(CreateDistrictModel(159, "Savaştepe", 12));
        districtModels.Add(CreateDistrictModel(160, "Sındırgı", 12));
        districtModels.Add(CreateDistrictModel(161, "Susurluk", 12));
        districtModels.Add(CreateDistrictModel(162, "Amasra", 13));
        districtModels.Add(CreateDistrictModel(163, "Kurucaşile", 13));
        districtModels.Add(CreateDistrictModel(164, "Merkez", 13));
        districtModels.Add(CreateDistrictModel(165, "Ulus", 13));
        districtModels.Add(CreateDistrictModel(166, "Beşiri", 14));
        districtModels.Add(CreateDistrictModel(167, "Gercüş", 14));
        districtModels.Add(CreateDistrictModel(168, "Hasankeyf", 14));
        districtModels.Add(CreateDistrictModel(169, "Kozluk", 14));
        districtModels.Add(CreateDistrictModel(170, "Merkez", 14));
        districtModels.Add(CreateDistrictModel(171, "Sason", 14));
        districtModels.Add(CreateDistrictModel(172, "Aydıntepe", 15));
        districtModels.Add(CreateDistrictModel(173, "Demirözü", 15));
        districtModels.Add(CreateDistrictModel(174, "Merkez", 15));
        districtModels.Add(CreateDistrictModel(175, "Bozüyük", 16));
        districtModels.Add(CreateDistrictModel(176, "Gölpazarı", 16));
        districtModels.Add(CreateDistrictModel(177, "İnhisar", 16));
        districtModels.Add(CreateDistrictModel(178, "Merkez", 16));
        districtModels.Add(CreateDistrictModel(179, "Osmaneli", 16));
        districtModels.Add(CreateDistrictModel(180, "Pazaryeri", 16));
        districtModels.Add(CreateDistrictModel(181, "Söğüt", 16));
        districtModels.Add(CreateDistrictModel(182, "Yenipazar", 16));
        districtModels.Add(CreateDistrictModel(183, "Adaklı", 17));
        districtModels.Add(CreateDistrictModel(184, "Genç", 17));
        districtModels.Add(CreateDistrictModel(185, "Karlıova", 17));
        districtModels.Add(CreateDistrictModel(186, "Kiğı", 17));
        districtModels.Add(CreateDistrictModel(187, "Merkez", 17));
        districtModels.Add(CreateDistrictModel(188, "Solhan", 17));
        districtModels.Add(CreateDistrictModel(189, "Yayladere", 17));
        districtModels.Add(CreateDistrictModel(190, "Yedisu", 17));
        districtModels.Add(CreateDistrictModel(191, "Adilcevaz", 18));
        districtModels.Add(CreateDistrictModel(192, "Ahlat", 18));
        districtModels.Add(CreateDistrictModel(193, "Güroymak", 18));
        districtModels.Add(CreateDistrictModel(194, "Hizan", 18));
        districtModels.Add(CreateDistrictModel(195, "Merkez", 18));
        districtModels.Add(CreateDistrictModel(196, "Mutki", 18));
        districtModels.Add(CreateDistrictModel(197, "Tatvan", 18));
        districtModels.Add(CreateDistrictModel(198, "Dörtdivan", 19));
        districtModels.Add(CreateDistrictModel(199, "Gerede", 19));
        districtModels.Add(CreateDistrictModel(200, "Göynük", 19));
        districtModels.Add(CreateDistrictModel(201, "Kıbrıscık", 19));
        districtModels.Add(CreateDistrictModel(202, "Mengen", 19));
        districtModels.Add(CreateDistrictModel(203, "Merkez", 19));
        districtModels.Add(CreateDistrictModel(204, "Mudurnu", 19));
        districtModels.Add(CreateDistrictModel(205, "Seben", 19));
        districtModels.Add(CreateDistrictModel(206, "Yeniçağa", 19));
        districtModels.Add(CreateDistrictModel(207, "Ağlasun", 20));
        districtModels.Add(CreateDistrictModel(208, "Altınyayla", 20));
        districtModels.Add(CreateDistrictModel(209, "Bucak", 20));
        districtModels.Add(CreateDistrictModel(210, "Çavdır", 20));
        districtModels.Add(CreateDistrictModel(211, "Çeltikçi", 20));
        districtModels.Add(CreateDistrictModel(212, "Gölhisar", 20));
        districtModels.Add(CreateDistrictModel(213, "Karamanlı", 20));
        districtModels.Add(CreateDistrictModel(214, "Kemer", 20));
        districtModels.Add(CreateDistrictModel(215, "Merkez", 20));
        districtModels.Add(CreateDistrictModel(216, "Tefenni", 20));
        districtModels.Add(CreateDistrictModel(217, "Yeşilova", 20));
        districtModels.Add(CreateDistrictModel(218, "Büyükorhan", 21));
        districtModels.Add(CreateDistrictModel(219, "Gemlik", 21));
        districtModels.Add(CreateDistrictModel(220, "Gürsu", 21));
        districtModels.Add(CreateDistrictModel(221, "Harmancık", 21));
        districtModels.Add(CreateDistrictModel(222, "İnegöl", 21));
        districtModels.Add(CreateDistrictModel(223, "İznik", 21));
        districtModels.Add(CreateDistrictModel(224, "Karacabey", 21));
        districtModels.Add(CreateDistrictModel(225, "Keles", 21));
        districtModels.Add(CreateDistrictModel(226, "Kestel", 21));
        districtModels.Add(CreateDistrictModel(227, "Mudanya", 21));
        districtModels.Add(CreateDistrictModel(228, "Mustafakemalpaşa", 21));
        districtModels.Add(CreateDistrictModel(229, "Nilüfer", 21));
        districtModels.Add(CreateDistrictModel(230, "Orhaneli", 21));
        districtModels.Add(CreateDistrictModel(231, "Orhangazi", 21));
        districtModels.Add(CreateDistrictModel(232, "Osmangazi", 21));
        districtModels.Add(CreateDistrictModel(233, "Yenişehir", 21));
        districtModels.Add(CreateDistrictModel(234, "Yıldırım", 21));
        districtModels.Add(CreateDistrictModel(235, "Ayvacık", 22));
        districtModels.Add(CreateDistrictModel(236, "Bayramiç", 22));
        districtModels.Add(CreateDistrictModel(237, "Biga", 22));
        districtModels.Add(CreateDistrictModel(238, "Bozcaada", 22));
        districtModels.Add(CreateDistrictModel(239, "Çan", 22));
        districtModels.Add(CreateDistrictModel(240, "Eceabat", 22));
        districtModels.Add(CreateDistrictModel(241, "Ezine", 22));
        districtModels.Add(CreateDistrictModel(242, "Gelibolu", 22));
        districtModels.Add(CreateDistrictModel(243, "Gökçeada", 22));
        districtModels.Add(CreateDistrictModel(244, "Lapseki", 22));
        districtModels.Add(CreateDistrictModel(245, "Merkez", 22));
        districtModels.Add(CreateDistrictModel(246, "Yenice", 22));
        districtModels.Add(CreateDistrictModel(247, "Atkaracalar", 23));
        districtModels.Add(CreateDistrictModel(248, "Bayramören", 23));
        districtModels.Add(CreateDistrictModel(249, "Çerkeş", 23));
        districtModels.Add(CreateDistrictModel(250, "Eldivan", 23));
        districtModels.Add(CreateDistrictModel(251, "Ilgaz", 23));
        districtModels.Add(CreateDistrictModel(252, "Kızılırmak", 23));
        districtModels.Add(CreateDistrictModel(253, "Korgun", 23));
        districtModels.Add(CreateDistrictModel(254, "Kurşunlu", 23));
        districtModels.Add(CreateDistrictModel(255, "Merkez", 23));
        districtModels.Add(CreateDistrictModel(256, "Orta", 23));
        districtModels.Add(CreateDistrictModel(257, "Şabanözü", 23));
        districtModels.Add(CreateDistrictModel(258, "Yapraklı", 23));
        districtModels.Add(CreateDistrictModel(259, "Alaca", 24));
        districtModels.Add(CreateDistrictModel(260, "Bayat", 24));
        districtModels.Add(CreateDistrictModel(261, "Boğazkale", 24));
        districtModels.Add(CreateDistrictModel(262, "Dodurga", 24));
        districtModels.Add(CreateDistrictModel(263, "İskilip", 24));
        districtModels.Add(CreateDistrictModel(264, "Kargı", 24));
        districtModels.Add(CreateDistrictModel(265, "Laçin", 24));
        districtModels.Add(CreateDistrictModel(266, "Mecitözü", 24));
        districtModels.Add(CreateDistrictModel(267, "Merkez", 24));
        districtModels.Add(CreateDistrictModel(268, "Oğuzlar", 24));
        districtModels.Add(CreateDistrictModel(269, "Ortaköy", 24));
        districtModels.Add(CreateDistrictModel(270, "Osmancık", 24));
        districtModels.Add(CreateDistrictModel(271, "Sungurlu", 24));
        districtModels.Add(CreateDistrictModel(272, "Uğurludağ", 24));
        districtModels.Add(CreateDistrictModel(273, "Acıpayam", 25));
        districtModels.Add(CreateDistrictModel(274, "Babadağ", 25));
        districtModels.Add(CreateDistrictModel(275, "Baklan", 25));
        districtModels.Add(CreateDistrictModel(276, "Bekilli", 25));
        districtModels.Add(CreateDistrictModel(277, "Beyağaç", 25));
        districtModels.Add(CreateDistrictModel(278, "Bozkurt", 25));
        districtModels.Add(CreateDistrictModel(279, "Buldan", 25));
        districtModels.Add(CreateDistrictModel(280, "Çal", 25));
        districtModels.Add(CreateDistrictModel(281, "Çameli", 25));
        districtModels.Add(CreateDistrictModel(282, "Çardak", 25));
        districtModels.Add(CreateDistrictModel(283, "Çivril", 25));
        districtModels.Add(CreateDistrictModel(284, "Güney", 25));
        districtModels.Add(CreateDistrictModel(285, "Honaz", 25));
        districtModels.Add(CreateDistrictModel(286, "Kale", 25));
        districtModels.Add(CreateDistrictModel(287, "Merkezefendi", 25));
        districtModels.Add(CreateDistrictModel(288, "Pamukkale", 25));
        districtModels.Add(CreateDistrictModel(289, "Sarayköy", 25));
        districtModels.Add(CreateDistrictModel(290, "Serinhisar", 25));
        districtModels.Add(CreateDistrictModel(291, "Tavas", 25));
        districtModels.Add(CreateDistrictModel(292, "Bağlar", 26));
        districtModels.Add(CreateDistrictModel(293, "Bismil", 26));
        districtModels.Add(CreateDistrictModel(294, "Çermik", 26));
        districtModels.Add(CreateDistrictModel(295, "Çınar", 26));
        districtModels.Add(CreateDistrictModel(296, "Çüngüş", 26));
        districtModels.Add(CreateDistrictModel(297, "Dicle", 26));
        districtModels.Add(CreateDistrictModel(298, "Eğil", 26));
        districtModels.Add(CreateDistrictModel(299, "Ergani", 26));
        districtModels.Add(CreateDistrictModel(300, "Hani", 26));
        districtModels.Add(CreateDistrictModel(301, "Hazro", 26));
        districtModels.Add(CreateDistrictModel(302, "Kayapınar", 26));
        districtModels.Add(CreateDistrictModel(303, "Kocaköy", 26));
        districtModels.Add(CreateDistrictModel(304, "Kulp", 26));
        districtModels.Add(CreateDistrictModel(305, "Lice", 26));
        districtModels.Add(CreateDistrictModel(306, "Silvan", 26));
        districtModels.Add(CreateDistrictModel(307, "Sur", 26));
        districtModels.Add(CreateDistrictModel(308, "Yenişehir", 26));
        districtModels.Add(CreateDistrictModel(309, "Akçakoca", 27));
        districtModels.Add(CreateDistrictModel(310, "Çilimli", 27));
        districtModels.Add(CreateDistrictModel(311, "Cumayeri", 27));
        districtModels.Add(CreateDistrictModel(312, "Gölyaka", 27));
        districtModels.Add(CreateDistrictModel(313, "Gümüşova", 27));
        districtModels.Add(CreateDistrictModel(314, "Kaynaşlı", 27));
        districtModels.Add(CreateDistrictModel(315, "Merkez", 27));
        districtModels.Add(CreateDistrictModel(316, "Yığılca", 27));
        districtModels.Add(CreateDistrictModel(317, "Enez", 28));
        districtModels.Add(CreateDistrictModel(318, "Havsa", 28));
        districtModels.Add(CreateDistrictModel(319, "İpsala", 28));
        districtModels.Add(CreateDistrictModel(320, "Keşan", 28));
        districtModels.Add(CreateDistrictModel(321, "Lalapaşa", 28));
        districtModels.Add(CreateDistrictModel(322, "Meriç", 28));
        districtModels.Add(CreateDistrictModel(323, "Merkez", 28));
        districtModels.Add(CreateDistrictModel(324, "Süloğlu", 28));
        districtModels.Add(CreateDistrictModel(325, "Uzunköprü", 28));
        districtModels.Add(CreateDistrictModel(326, "Ağın", 29));
        districtModels.Add(CreateDistrictModel(327, "Alacakaya", 29));
        districtModels.Add(CreateDistrictModel(328, "Arıcak", 29));
        districtModels.Add(CreateDistrictModel(329, "Baskil", 29));
        districtModels.Add(CreateDistrictModel(330, "Karakoçan", 29));
        districtModels.Add(CreateDistrictModel(331, "Keban", 29));
        districtModels.Add(CreateDistrictModel(332, "Kovancılar", 29));
        districtModels.Add(CreateDistrictModel(333, "Maden", 29));
        districtModels.Add(CreateDistrictModel(334, "Merkez", 29));
        districtModels.Add(CreateDistrictModel(335, "Palu", 29));
        districtModels.Add(CreateDistrictModel(336, "Sivrice", 29));
        districtModels.Add(CreateDistrictModel(337, "Çayırlı", 30));
        districtModels.Add(CreateDistrictModel(338, "İliç", 30));
        districtModels.Add(CreateDistrictModel(339, "Kemah", 30));
        districtModels.Add(CreateDistrictModel(340, "Kemaliye", 30));
        districtModels.Add(CreateDistrictModel(341, "Merkez", 30));
        districtModels.Add(CreateDistrictModel(342, "Otlukbeli", 30));
        districtModels.Add(CreateDistrictModel(343, "Refahiye", 30));
        districtModels.Add(CreateDistrictModel(344, "Tercan", 30));
        districtModels.Add(CreateDistrictModel(345, "Üzümlü", 30));
        districtModels.Add(CreateDistrictModel(346, "Aşkale", 31));
        districtModels.Add(CreateDistrictModel(347, "Aziziye", 31));
        districtModels.Add(CreateDistrictModel(348, "Çat", 31));
        districtModels.Add(CreateDistrictModel(349, "Hınıs", 31));
        districtModels.Add(CreateDistrictModel(350, "Horasan", 31));
        districtModels.Add(CreateDistrictModel(351, "İspir", 31));
        districtModels.Add(CreateDistrictModel(352, "Karaçoban", 31));
        districtModels.Add(CreateDistrictModel(353, "Karayazı", 31));
        districtModels.Add(CreateDistrictModel(354, "Köprüköy", 31));
        districtModels.Add(CreateDistrictModel(355, "Narman", 31));
        districtModels.Add(CreateDistrictModel(356, "Oltu", 31));
        districtModels.Add(CreateDistrictModel(357, "Olur", 31));
        districtModels.Add(CreateDistrictModel(358, "Palandöken", 31));
        districtModels.Add(CreateDistrictModel(359, "Pasinler", 31));
        districtModels.Add(CreateDistrictModel(360, "Pazaryolu", 31));
        districtModels.Add(CreateDistrictModel(361, "Şenkaya", 31));
        districtModels.Add(CreateDistrictModel(362, "Tekman", 31));
        districtModels.Add(CreateDistrictModel(363, "Tortum", 31));
        districtModels.Add(CreateDistrictModel(364, "Uzundere", 31));
        districtModels.Add(CreateDistrictModel(365, "Yakutiye", 31));
        districtModels.Add(CreateDistrictModel(366, "Alpu", 32));
        districtModels.Add(CreateDistrictModel(367, "Beylikova", 32));
        districtModels.Add(CreateDistrictModel(368, "Çifteler", 32));
        districtModels.Add(CreateDistrictModel(369, "Günyüzü", 32));
        districtModels.Add(CreateDistrictModel(370, "Han", 32));
        districtModels.Add(CreateDistrictModel(371, "İnönü", 32));
        districtModels.Add(CreateDistrictModel(372, "Mahmudiye", 32));
        districtModels.Add(CreateDistrictModel(373, "Mihalgazi", 32));
        districtModels.Add(CreateDistrictModel(374, "Mihalıççık", 32));
        districtModels.Add(CreateDistrictModel(375, "Odunpazarı", 32));
        districtModels.Add(CreateDistrictModel(376, "Sarıcakaya", 32));
        districtModels.Add(CreateDistrictModel(377, "Seyitgazi", 32));
        districtModels.Add(CreateDistrictModel(378, "Sivrihisar", 32));
        districtModels.Add(CreateDistrictModel(379, "Tepebaşı", 32));
        districtModels.Add(CreateDistrictModel(380, "Araban", 33));
        districtModels.Add(CreateDistrictModel(381, "İslahiye", 33));
        districtModels.Add(CreateDistrictModel(382, "Karkamış", 33));
        districtModels.Add(CreateDistrictModel(383, "Nizip", 33));
        districtModels.Add(CreateDistrictModel(384, "Nurdağı", 33));
        districtModels.Add(CreateDistrictModel(385, "Oğuzeli", 33));
        districtModels.Add(CreateDistrictModel(386, "Şahinbey", 33));
        districtModels.Add(CreateDistrictModel(387, "Şehitkamil", 33));
        districtModels.Add(CreateDistrictModel(388, "Yavuzeli", 33));
        districtModels.Add(CreateDistrictModel(389, "Alucra", 34));
        districtModels.Add(CreateDistrictModel(390, "Bulancak", 34));
        districtModels.Add(CreateDistrictModel(391, "Çamoluk", 34));
        districtModels.Add(CreateDistrictModel(392, "Çanakçı", 34));
        districtModels.Add(CreateDistrictModel(393, "Dereli", 34));
        districtModels.Add(CreateDistrictModel(394, "Doğankent", 34));
        districtModels.Add(CreateDistrictModel(395, "Espiye", 34));
        districtModels.Add(CreateDistrictModel(396, "Eynesil", 34));
        districtModels.Add(CreateDistrictModel(397, "Görele", 34));
        districtModels.Add(CreateDistrictModel(398, "Güce", 34));
        districtModels.Add(CreateDistrictModel(399, "Keşap", 34));
        districtModels.Add(CreateDistrictModel(400, "Merkez", 34));
        districtModels.Add(CreateDistrictModel(401, "Piraziz", 34));
        districtModels.Add(CreateDistrictModel(402, "Şebinkarahisar", 34));
        districtModels.Add(CreateDistrictModel(403, "Tirebolu", 34));
        districtModels.Add(CreateDistrictModel(404, "Yağlıdere", 34));
        districtModels.Add(CreateDistrictModel(405, "Kelkit", 35));
        districtModels.Add(CreateDistrictModel(406, "Köse", 35));
        districtModels.Add(CreateDistrictModel(407, "Kürtün", 35));
        districtModels.Add(CreateDistrictModel(408, "Merkez", 35));
        districtModels.Add(CreateDistrictModel(409, "Şiran", 35));
        districtModels.Add(CreateDistrictModel(410, "Torul", 35));
        districtModels.Add(CreateDistrictModel(411, "Çukurca", 36));
        districtModels.Add(CreateDistrictModel(412, "Derecik", 36));
        districtModels.Add(CreateDistrictModel(413, "Merkez", 36));
        districtModels.Add(CreateDistrictModel(414, "Şemdinli", 36));
        districtModels.Add(CreateDistrictModel(415, "Yüksekova", 36));
        districtModels.Add(CreateDistrictModel(416, "Altınözü", 37));
        districtModels.Add(CreateDistrictModel(417, "Antakya", 37));
        districtModels.Add(CreateDistrictModel(418, "Arsuz", 37));
        districtModels.Add(CreateDistrictModel(419, "Belen", 37));
        districtModels.Add(CreateDistrictModel(420, "Defne", 37));
        districtModels.Add(CreateDistrictModel(421, "Dörtyol", 37));
        districtModels.Add(CreateDistrictModel(422, "Erzin", 37));
        districtModels.Add(CreateDistrictModel(423, "Hassa", 37));
        districtModels.Add(CreateDistrictModel(424, "İskenderun", 37));
        districtModels.Add(CreateDistrictModel(425, "Kırıkhan", 37));
        districtModels.Add(CreateDistrictModel(426, "Kumlu", 37));
        districtModels.Add(CreateDistrictModel(427, "Payas", 37));
        districtModels.Add(CreateDistrictModel(428, "Reyhanlı", 37));
        districtModels.Add(CreateDistrictModel(429, "Samandağ", 37));
        districtModels.Add(CreateDistrictModel(430, "Yayladağı", 37));
        districtModels.Add(CreateDistrictModel(431, "Aralık", 38));
        districtModels.Add(CreateDistrictModel(432, "Karakoyunlu", 38));
        districtModels.Add(CreateDistrictModel(433, "Merkez", 38));
        districtModels.Add(CreateDistrictModel(434, "Tuzluca", 38));
        districtModels.Add(CreateDistrictModel(435, "Aksu", 39));
        districtModels.Add(CreateDistrictModel(436, "Atabey", 39));
        districtModels.Add(CreateDistrictModel(437, "Eğirdir", 39));
        districtModels.Add(CreateDistrictModel(438, "Gelendost", 39));
        districtModels.Add(CreateDistrictModel(439, "Gönen", 39));
        districtModels.Add(CreateDistrictModel(440, "Keçiborlu", 39));
        districtModels.Add(CreateDistrictModel(441, "Merkez", 39));
        districtModels.Add(CreateDistrictModel(442, "Şarkikaraağaç", 39));
        districtModels.Add(CreateDistrictModel(443, "Senirkent", 39));
        districtModels.Add(CreateDistrictModel(444, "Sütçüler", 39));
        districtModels.Add(CreateDistrictModel(445, "Uluborlu", 39));
        districtModels.Add(CreateDistrictModel(446, "Yalvaç", 39));
        districtModels.Add(CreateDistrictModel(447, "Yenişarbademli", 39));
        districtModels.Add(CreateDistrictModel(448, "Adalar", 40));
        districtModels.Add(CreateDistrictModel(449, "Arnavutköy", 40));
        districtModels.Add(CreateDistrictModel(450, "Ataşehir", 40));
        districtModels.Add(CreateDistrictModel(451, "Avcılar", 40));
        districtModels.Add(CreateDistrictModel(452, "Bağcılar", 40));
        districtModels.Add(CreateDistrictModel(453, "Bahçelievler", 40));
        districtModels.Add(CreateDistrictModel(454, "Bakırköy", 40));
        districtModels.Add(CreateDistrictModel(455, "Başakşehir", 40));
        districtModels.Add(CreateDistrictModel(456, "Bayrampaşa", 40));
        districtModels.Add(CreateDistrictModel(457, "Beşiktaş", 40));
        districtModels.Add(CreateDistrictModel(458, "Beykoz", 40));
        districtModels.Add(CreateDistrictModel(459, "Beylikdüzü", 40));
        districtModels.Add(CreateDistrictModel(460, "Beyoğlu", 40));
        districtModels.Add(CreateDistrictModel(461, "Büyükçekmece", 40));
        districtModels.Add(CreateDistrictModel(462, "Çatalca", 40));
        districtModels.Add(CreateDistrictModel(463, "Çekmeköy", 40));
        districtModels.Add(CreateDistrictModel(464, "Esenler", 40));
        districtModels.Add(CreateDistrictModel(465, "Esenyurt", 40));
        districtModels.Add(CreateDistrictModel(466, "Eyüpsultan", 40));
        districtModels.Add(CreateDistrictModel(467, "Fatih", 40));
        districtModels.Add(CreateDistrictModel(468, "Gaziosmanpaşa", 40));
        districtModels.Add(CreateDistrictModel(469, "Güngören", 40));
        districtModels.Add(CreateDistrictModel(470, "Kadıköy", 40));
        districtModels.Add(CreateDistrictModel(471, "Kağıthane", 40));
        districtModels.Add(CreateDistrictModel(472, "Kartal", 40));
        districtModels.Add(CreateDistrictModel(473, "Küçükçekmece", 40));
        districtModels.Add(CreateDistrictModel(474, "Maltepe", 40));
        districtModels.Add(CreateDistrictModel(475, "Pendik", 40));
        districtModels.Add(CreateDistrictModel(476, "Sancaktepe", 40));
        districtModels.Add(CreateDistrictModel(477, "Sarıyer", 40));
        districtModels.Add(CreateDistrictModel(478, "Şile", 40));
        districtModels.Add(CreateDistrictModel(479, "Silivri", 40));
        districtModels.Add(CreateDistrictModel(480, "Şişli", 40));
        districtModels.Add(CreateDistrictModel(481, "Sultanbeyli", 40));
        districtModels.Add(CreateDistrictModel(482, "Sultangazi", 40));
        districtModels.Add(CreateDistrictModel(483, "Tuzla", 40));
        districtModels.Add(CreateDistrictModel(484, "Ümraniye", 40));
        districtModels.Add(CreateDistrictModel(485, "Üsküdar", 40));
        districtModels.Add(CreateDistrictModel(486, "Zeytinburnu", 40));
        districtModels.Add(CreateDistrictModel(487, "Aliağa", 41));
        districtModels.Add(CreateDistrictModel(488, "Balçova", 41));
        districtModels.Add(CreateDistrictModel(489, "Bayındır", 41));
        districtModels.Add(CreateDistrictModel(490, "Bayraklı", 41));
        districtModels.Add(CreateDistrictModel(491, "Bergama", 41));
        districtModels.Add(CreateDistrictModel(492, "Beydağ", 41));
        districtModels.Add(CreateDistrictModel(493, "Bornova", 41));
        districtModels.Add(CreateDistrictModel(494, "Buca", 41));
        districtModels.Add(CreateDistrictModel(495, "Çeşme", 41));
        districtModels.Add(CreateDistrictModel(496, "Çiğli", 41));
        districtModels.Add(CreateDistrictModel(497, "Dikili", 41));
        districtModels.Add(CreateDistrictModel(498, "Foça", 41));
        districtModels.Add(CreateDistrictModel(499, "Gaziemir", 41));
        districtModels.Add(CreateDistrictModel(500, "Güzelbahçe", 41));
        districtModels.Add(CreateDistrictModel(501, "Karabağlar", 41));
        districtModels.Add(CreateDistrictModel(502, "Karaburun", 41));
        districtModels.Add(CreateDistrictModel(503, "Karşıyaka", 41));
        districtModels.Add(CreateDistrictModel(504, "Kemalpaşa", 41));
        districtModels.Add(CreateDistrictModel(505, "Kınık", 41));
        districtModels.Add(CreateDistrictModel(506, "Kiraz", 41));
        districtModels.Add(CreateDistrictModel(507, "Konak", 41));
        districtModels.Add(CreateDistrictModel(508, "Menderes", 41));
        districtModels.Add(CreateDistrictModel(509, "Menemen", 41));
        districtModels.Add(CreateDistrictModel(510, "Narlıdere", 41));
        districtModels.Add(CreateDistrictModel(511, "Ödemiş", 41));
        districtModels.Add(CreateDistrictModel(512, "Seferihisar", 41));
        districtModels.Add(CreateDistrictModel(513, "Selçuk", 41));
        districtModels.Add(CreateDistrictModel(514, "Tire", 41));
        districtModels.Add(CreateDistrictModel(515, "Torbalı", 41));
        districtModels.Add(CreateDistrictModel(516, "Urla", 41));
        districtModels.Add(CreateDistrictModel(517, "Afşin", 42));
        districtModels.Add(CreateDistrictModel(518, "Andırın", 42));
        districtModels.Add(CreateDistrictModel(519, "Çağlayancerit", 42));
        districtModels.Add(CreateDistrictModel(520, "Dulkadiroğlu", 42));
        districtModels.Add(CreateDistrictModel(521, "Ekinözü", 42));
        districtModels.Add(CreateDistrictModel(522, "Elbistan", 42));
        districtModels.Add(CreateDistrictModel(523, "Göksun", 42));
        districtModels.Add(CreateDistrictModel(524, "Nurhak", 42));
        districtModels.Add(CreateDistrictModel(525, "Onikişubat", 42));
        districtModels.Add(CreateDistrictModel(526, "Pazarcık", 42));
        districtModels.Add(CreateDistrictModel(527, "Türkoğlu", 42));
        districtModels.Add(CreateDistrictModel(528, "Eflani", 43));
        districtModels.Add(CreateDistrictModel(529, "Eskipazar", 43));
        districtModels.Add(CreateDistrictModel(530, "Merkez", 43));
        districtModels.Add(CreateDistrictModel(531, "Ovacık", 43));
        districtModels.Add(CreateDistrictModel(532, "Safranbolu", 43));
        districtModels.Add(CreateDistrictModel(533, "Yenice", 43));
        districtModels.Add(CreateDistrictModel(534, "Ayrancı", 44));
        districtModels.Add(CreateDistrictModel(535, "Başyayla", 44));
        districtModels.Add(CreateDistrictModel(536, "Ermenek", 44));
        districtModels.Add(CreateDistrictModel(537, "Kazımkarabekir", 44));
        districtModels.Add(CreateDistrictModel(538, "Merkez", 44));
        districtModels.Add(CreateDistrictModel(539, "Sarıveliler", 44));
        districtModels.Add(CreateDistrictModel(540, "Akyaka", 45));
        districtModels.Add(CreateDistrictModel(541, "Arpaçay", 45));
        districtModels.Add(CreateDistrictModel(542, "Digor", 45));
        districtModels.Add(CreateDistrictModel(543, "Kağızman", 45));
        districtModels.Add(CreateDistrictModel(544, "Merkez", 45));
        districtModels.Add(CreateDistrictModel(545, "Sarıkamış", 45));
        districtModels.Add(CreateDistrictModel(546, "Selim", 45));
        districtModels.Add(CreateDistrictModel(547, "Susuz", 45));
        districtModels.Add(CreateDistrictModel(548, "Abana", 46));
        districtModels.Add(CreateDistrictModel(549, "Ağlı", 46));
        districtModels.Add(CreateDistrictModel(550, "Araç", 46));
        districtModels.Add(CreateDistrictModel(551, "Azdavay", 46));
        districtModels.Add(CreateDistrictModel(552, "Bozkurt", 46));
        districtModels.Add(CreateDistrictModel(553, "Çatalzeytin", 46));
        districtModels.Add(CreateDistrictModel(554, "Cide", 46));
        districtModels.Add(CreateDistrictModel(555, "Daday", 46));
        districtModels.Add(CreateDistrictModel(556, "Devrekani", 46));
        districtModels.Add(CreateDistrictModel(557, "Doğanyurt", 46));
        districtModels.Add(CreateDistrictModel(558, "Hanönü", 46));
        districtModels.Add(CreateDistrictModel(559, "İhsangazi", 46));
        districtModels.Add(CreateDistrictModel(560, "İnebolu", 46));
        districtModels.Add(CreateDistrictModel(561, "Küre", 46));
        districtModels.Add(CreateDistrictModel(562, "Merkez", 46));
        districtModels.Add(CreateDistrictModel(563, "Pınarbaşı", 46));
        districtModels.Add(CreateDistrictModel(564, "Şenpazar", 46));
        districtModels.Add(CreateDistrictModel(565, "Seydiler", 46));
        districtModels.Add(CreateDistrictModel(566, "Taşköprü", 46));
        districtModels.Add(CreateDistrictModel(567, "Tosya", 46));
        districtModels.Add(CreateDistrictModel(568, "Akkışla", 47));
        districtModels.Add(CreateDistrictModel(569, "Bünyan", 47));
        districtModels.Add(CreateDistrictModel(570, "Develi", 47));
        districtModels.Add(CreateDistrictModel(571, "Felahiye", 47));
        districtModels.Add(CreateDistrictModel(572, "Hacılar", 47));
        districtModels.Add(CreateDistrictModel(573, "İncesu", 47));
        districtModels.Add(CreateDistrictModel(574, "Kocasinan", 47));
        districtModels.Add(CreateDistrictModel(575, "Melikgazi", 47));
        districtModels.Add(CreateDistrictModel(576, "Özvatan", 47));
        districtModels.Add(CreateDistrictModel(577, "Pınarbaşı", 47));
        districtModels.Add(CreateDistrictModel(578, "Sarıoğlan", 47));
        districtModels.Add(CreateDistrictModel(579, "Sarız", 47));
        districtModels.Add(CreateDistrictModel(580, "Talas", 47));
        districtModels.Add(CreateDistrictModel(581, "Tomarza", 47));
        districtModels.Add(CreateDistrictModel(582, "Yahyalı", 47));
        districtModels.Add(CreateDistrictModel(583, "Yeşilhisar", 47));
        districtModels.Add(CreateDistrictModel(584, "Elbeyli", 48));
        districtModels.Add(CreateDistrictModel(585, "Merkez", 48));
        districtModels.Add(CreateDistrictModel(586, "Musabeyli", 48));
        districtModels.Add(CreateDistrictModel(587, "Polateli", 48));
        districtModels.Add(CreateDistrictModel(588, "Bahşılı", 49));
        districtModels.Add(CreateDistrictModel(589, "Balışeyh", 49));
        districtModels.Add(CreateDistrictModel(590, "Çelebi", 49));
        districtModels.Add(CreateDistrictModel(591, "Delice", 49));
        districtModels.Add(CreateDistrictModel(592, "Karakeçili", 49));
        districtModels.Add(CreateDistrictModel(593, "Keskin", 49));
        districtModels.Add(CreateDistrictModel(594, "Merkez", 49));
        districtModels.Add(CreateDistrictModel(595, "Sulakyurt", 49));
        districtModels.Add(CreateDistrictModel(596, "Yahşihan", 49));
        districtModels.Add(CreateDistrictModel(597, "Babaeski", 50));
        districtModels.Add(CreateDistrictModel(598, "Demirköy", 50));
        districtModels.Add(CreateDistrictModel(599, "Kofçaz", 50));
        districtModels.Add(CreateDistrictModel(600, "Lüleburgaz", 50));
        districtModels.Add(CreateDistrictModel(601, "Merkez", 50));
        districtModels.Add(CreateDistrictModel(602, "Pehlivanköy", 50));
        districtModels.Add(CreateDistrictModel(603, "Pınarhisar", 50));
        districtModels.Add(CreateDistrictModel(604, "Vize", 50));
        districtModels.Add(CreateDistrictModel(605, "Akçakent", 51));
        districtModels.Add(CreateDistrictModel(606, "Akpınar", 51));
        districtModels.Add(CreateDistrictModel(607, "Boztepe", 51));
        districtModels.Add(CreateDistrictModel(608, "Çiçekdağı", 51));
        districtModels.Add(CreateDistrictModel(609, "Kaman", 51));
        districtModels.Add(CreateDistrictModel(610, "Merkez", 51));
        districtModels.Add(CreateDistrictModel(611, "Mucur", 51));
        districtModels.Add(CreateDistrictModel(612, "Başiskele", 52));
        districtModels.Add(CreateDistrictModel(613, "Çayırova", 52));
        districtModels.Add(CreateDistrictModel(614, "Darıca", 52));
        districtModels.Add(CreateDistrictModel(615, "Derince", 52));
        districtModels.Add(CreateDistrictModel(616, "Dilovası", 52));
        districtModels.Add(CreateDistrictModel(617, "Gebze", 52));
        districtModels.Add(CreateDistrictModel(618, "Gölcük", 52));
        districtModels.Add(CreateDistrictModel(619, "İzmit", 52));
        districtModels.Add(CreateDistrictModel(620, "Kandıra", 52));
        districtModels.Add(CreateDistrictModel(621, "Karamürsel", 52));
        districtModels.Add(CreateDistrictModel(622, "Kartepe", 52));
        districtModels.Add(CreateDistrictModel(623, "Körfez", 52));
        districtModels.Add(CreateDistrictModel(624, "Ahırlı", 53));
        districtModels.Add(CreateDistrictModel(625, "Akören", 53));
        districtModels.Add(CreateDistrictModel(626, "Akşehir", 53));
        districtModels.Add(CreateDistrictModel(627, "Altınekin", 53));
        districtModels.Add(CreateDistrictModel(628, "Beyşehir", 53));
        districtModels.Add(CreateDistrictModel(629, "Bozkır", 53));
        districtModels.Add(CreateDistrictModel(630, "Çeltik", 53));
        districtModels.Add(CreateDistrictModel(631, "Cihanbeyli", 53));
        districtModels.Add(CreateDistrictModel(632, "Çumra", 53));
        districtModels.Add(CreateDistrictModel(633, "Derbent", 53));
        districtModels.Add(CreateDistrictModel(634, "Derebucak", 53));
        districtModels.Add(CreateDistrictModel(635, "Doğanhisar", 53));
        districtModels.Add(CreateDistrictModel(636, "Emirgazi", 53));
        districtModels.Add(CreateDistrictModel(637, "Ereğli", 53));
        districtModels.Add(CreateDistrictModel(638, "Güneysınır", 53));
        districtModels.Add(CreateDistrictModel(639, "Hadim", 53));
        districtModels.Add(CreateDistrictModel(640, "Halkapınar", 53));
        districtModels.Add(CreateDistrictModel(641, "Hüyük", 53));
        districtModels.Add(CreateDistrictModel(642, "Ilgın", 53));
        districtModels.Add(CreateDistrictModel(643, "Kadınhanı", 53));
        districtModels.Add(CreateDistrictModel(644, "Karapınar", 53));
        districtModels.Add(CreateDistrictModel(645, "Karatay", 53));
        districtModels.Add(CreateDistrictModel(646, "Kulu", 53));
        districtModels.Add(CreateDistrictModel(647, "Meram", 53));
        districtModels.Add(CreateDistrictModel(648, "Sarayönü", 53));
        districtModels.Add(CreateDistrictModel(649, "Selçuklu", 53));
        districtModels.Add(CreateDistrictModel(650, "Seydişehir", 53));
        districtModels.Add(CreateDistrictModel(651, "Taşkent", 53));
        districtModels.Add(CreateDistrictModel(652, "Tuzlukçu", 53));
        districtModels.Add(CreateDistrictModel(653, "Yalıhüyük", 53));
        districtModels.Add(CreateDistrictModel(654, "Yunak", 53));
        districtModels.Add(CreateDistrictModel(655, "Altıntaş", 54));
        districtModels.Add(CreateDistrictModel(656, "Aslanapa", 54));
        districtModels.Add(CreateDistrictModel(657, "Çavdarhisar", 54));
        districtModels.Add(CreateDistrictModel(658, "Domaniç", 54));
        districtModels.Add(CreateDistrictModel(659, "Dumlupınar", 54));
        districtModels.Add(CreateDistrictModel(660, "Emet", 54));
        districtModels.Add(CreateDistrictModel(661, "Gediz", 54));
        districtModels.Add(CreateDistrictModel(662, "Hisarcık", 54));
        districtModels.Add(CreateDistrictModel(663, "Merkez", 54));
        districtModels.Add(CreateDistrictModel(664, "Pazarlar", 54));
        districtModels.Add(CreateDistrictModel(665, "Şaphane", 54));
        districtModels.Add(CreateDistrictModel(666, "Simav", 54));
        districtModels.Add(CreateDistrictModel(667, "Tavşanlı", 54));
        districtModels.Add(CreateDistrictModel(668, "Akçadağ", 55));
        districtModels.Add(CreateDistrictModel(669, "Arapgir", 55));
        districtModels.Add(CreateDistrictModel(670, "Arguvan", 55));
        districtModels.Add(CreateDistrictModel(671, "Battalgazi", 55));
        districtModels.Add(CreateDistrictModel(672, "Darende", 55));
        districtModels.Add(CreateDistrictModel(673, "Doğanşehir", 55));
        districtModels.Add(CreateDistrictModel(674, "Doğanyol", 55));
        districtModels.Add(CreateDistrictModel(675, "Hekimhan", 55));
        districtModels.Add(CreateDistrictModel(676, "Kale", 55));
        districtModels.Add(CreateDistrictModel(677, "Kuluncak", 55));
        districtModels.Add(CreateDistrictModel(678, "Pütürge", 55));
        districtModels.Add(CreateDistrictModel(679, "Yazıhan", 55));
        districtModels.Add(CreateDistrictModel(680, "Yeşilyurt", 55));
        districtModels.Add(CreateDistrictModel(681, "Ahmetli", 56));
        districtModels.Add(CreateDistrictModel(682, "Akhisar", 56));
        districtModels.Add(CreateDistrictModel(683, "Alaşehir", 56));
        districtModels.Add(CreateDistrictModel(684, "Demirci", 56));
        districtModels.Add(CreateDistrictModel(685, "Gölmarmara", 56));
        districtModels.Add(CreateDistrictModel(686, "Gördes", 56));
        districtModels.Add(CreateDistrictModel(687, "Kırkağaç", 56));
        districtModels.Add(CreateDistrictModel(688, "Köprübaşı", 56));
        districtModels.Add(CreateDistrictModel(689, "Kula", 56));
        districtModels.Add(CreateDistrictModel(690, "Salihli", 56));
        districtModels.Add(CreateDistrictModel(691, "Sarıgöl", 56));
        districtModels.Add(CreateDistrictModel(692, "Saruhanlı", 56));
        districtModels.Add(CreateDistrictModel(693, "Şehzadeler", 56));
        districtModels.Add(CreateDistrictModel(694, "Selendi", 56));
        districtModels.Add(CreateDistrictModel(695, "Soma", 56));
        districtModels.Add(CreateDistrictModel(696, "Turgutlu", 56));
        districtModels.Add(CreateDistrictModel(697, "Yunusemre", 56));
        districtModels.Add(CreateDistrictModel(698, "Artuklu", 57));
        districtModels.Add(CreateDistrictModel(699, "Dargeçit", 57));
        districtModels.Add(CreateDistrictModel(700, "Derik", 57));
        districtModels.Add(CreateDistrictModel(701, "Kızıltepe", 57));
        districtModels.Add(CreateDistrictModel(702, "Mazıdağı", 57));
        districtModels.Add(CreateDistrictModel(703, "Midyat", 57));
        districtModels.Add(CreateDistrictModel(704, "Nusaybin", 57));
        districtModels.Add(CreateDistrictModel(705, "Ömerli", 57));
        districtModels.Add(CreateDistrictModel(706, "Savur", 57));
        districtModels.Add(CreateDistrictModel(707, "Yeşilli", 57));
        districtModels.Add(CreateDistrictModel(708, "Akdeniz", 58));
        districtModels.Add(CreateDistrictModel(709, "Anamur", 58));
        districtModels.Add(CreateDistrictModel(710, "Aydıncık", 58));
        districtModels.Add(CreateDistrictModel(711, "Bozyazı", 58));
        districtModels.Add(CreateDistrictModel(712, "Çamlıyayla", 58));
        districtModels.Add(CreateDistrictModel(713, "Erdemli", 58));
        districtModels.Add(CreateDistrictModel(714, "Gülnar", 58));
        districtModels.Add(CreateDistrictModel(715, "Mezitli", 58));
        districtModels.Add(CreateDistrictModel(716, "Mut", 58));
        districtModels.Add(CreateDistrictModel(717, "Silifke", 58));
        districtModels.Add(CreateDistrictModel(718, "Tarsus", 58));
        districtModels.Add(CreateDistrictModel(719, "Toroslar", 58));
        districtModels.Add(CreateDistrictModel(720, "Yenişehir", 58));
        districtModels.Add(CreateDistrictModel(721, "Bodrum", 59));
        districtModels.Add(CreateDistrictModel(722, "Dalaman", 59));
        districtModels.Add(CreateDistrictModel(723, "Datça", 59));
        districtModels.Add(CreateDistrictModel(724, "Fethiye", 59));
        districtModels.Add(CreateDistrictModel(725, "Kavaklıdere", 59));
        districtModels.Add(CreateDistrictModel(726, "Köyceğiz", 59));
        districtModels.Add(CreateDistrictModel(727, "Marmaris", 59));
        districtModels.Add(CreateDistrictModel(728, "Menteşe", 59));
        districtModels.Add(CreateDistrictModel(729, "Milas", 59));
        districtModels.Add(CreateDistrictModel(730, "Ortaca", 59));
        districtModels.Add(CreateDistrictModel(731, "Seydikemer", 59));
        districtModels.Add(CreateDistrictModel(732, "Ula", 59));
        districtModels.Add(CreateDistrictModel(733, "Yatağan", 59));
        districtModels.Add(CreateDistrictModel(734, "Bulanık", 60));
        districtModels.Add(CreateDistrictModel(735, "Hasköy", 60));
        districtModels.Add(CreateDistrictModel(736, "Korkut", 60));
        districtModels.Add(CreateDistrictModel(737, "Malazgirt", 60));
        districtModels.Add(CreateDistrictModel(738, "Merkez", 60));
        districtModels.Add(CreateDistrictModel(739, "Varto", 60));
        districtModels.Add(CreateDistrictModel(740, "Acıgöl", 61));
        districtModels.Add(CreateDistrictModel(741, "Avanos", 61));
        districtModels.Add(CreateDistrictModel(742, "Derinkuyu", 61));
        districtModels.Add(CreateDistrictModel(743, "Gülşehir", 61));
        districtModels.Add(CreateDistrictModel(744, "Hacıbektaş", 61));
        districtModels.Add(CreateDistrictModel(745, "Kozaklı", 61));
        districtModels.Add(CreateDistrictModel(746, "Merkez", 61));
        districtModels.Add(CreateDistrictModel(747, "Ürgüp", 61));
        districtModels.Add(CreateDistrictModel(748, "Altunhisar", 62));
        districtModels.Add(CreateDistrictModel(749, "Bor", 62));
        districtModels.Add(CreateDistrictModel(750, "Çamardı", 62));
        districtModels.Add(CreateDistrictModel(751, "Çiftlik", 62));
        districtModels.Add(CreateDistrictModel(752, "Merkez", 62));
        districtModels.Add(CreateDistrictModel(753, "Ulukışla", 62));
        districtModels.Add(CreateDistrictModel(754, "Akkuş", 63));
        districtModels.Add(CreateDistrictModel(755, "Altınordu", 63));
        districtModels.Add(CreateDistrictModel(756, "Aybastı", 63));
        districtModels.Add(CreateDistrictModel(757, "Çamaş", 63));
        districtModels.Add(CreateDistrictModel(758, "Çatalpınar", 63));
        districtModels.Add(CreateDistrictModel(759, "Çaybaşı", 63));
        districtModels.Add(CreateDistrictModel(760, "Fatsa", 63));
        districtModels.Add(CreateDistrictModel(761, "Gölköy", 63));
        districtModels.Add(CreateDistrictModel(762, "Gülyalı", 63));
        districtModels.Add(CreateDistrictModel(763, "Gürgentepe", 63));
        districtModels.Add(CreateDistrictModel(764, "İkizce", 63));
        districtModels.Add(CreateDistrictModel(765, "Kabadüz", 63));
        districtModels.Add(CreateDistrictModel(766, "Kabataş", 63));
        districtModels.Add(CreateDistrictModel(767, "Korgan", 63));
        districtModels.Add(CreateDistrictModel(768, "Kumru", 63));
        districtModels.Add(CreateDistrictModel(769, "Mesudiye", 63));
        districtModels.Add(CreateDistrictModel(770, "Perşembe", 63));
        districtModels.Add(CreateDistrictModel(771, "Ulubey", 63));
        districtModels.Add(CreateDistrictModel(772, "Ünye", 63));
        districtModels.Add(CreateDistrictModel(773, "Bahçe", 64));
        districtModels.Add(CreateDistrictModel(774, "Düziçi", 64));
        districtModels.Add(CreateDistrictModel(775, "Hasanbeyli", 64));
        districtModels.Add(CreateDistrictModel(776, "Kadirli", 64));
        districtModels.Add(CreateDistrictModel(777, "Merkez", 64));
        districtModels.Add(CreateDistrictModel(778, "Sumbas", 64));
        districtModels.Add(CreateDistrictModel(779, "Toprakkale", 64));
        districtModels.Add(CreateDistrictModel(780, "Ardeşen", 65));
        districtModels.Add(CreateDistrictModel(781, "Çamlıhemşin", 65));
        districtModels.Add(CreateDistrictModel(782, "Çayeli", 65));
        districtModels.Add(CreateDistrictModel(783, "Derepazarı", 65));
        districtModels.Add(CreateDistrictModel(784, "Fındıklı", 65));
        districtModels.Add(CreateDistrictModel(785, "Güneysu", 65));
        districtModels.Add(CreateDistrictModel(786, "Hemşin", 65));
        districtModels.Add(CreateDistrictModel(787, "İkizdere", 65));
        districtModels.Add(CreateDistrictModel(788, "İyidere", 65));
        districtModels.Add(CreateDistrictModel(789, "Kalkandere", 65));
        districtModels.Add(CreateDistrictModel(790, "Merkez", 65));
        districtModels.Add(CreateDistrictModel(791, "Pazar", 65));
        districtModels.Add(CreateDistrictModel(792, "Adapazarı", 66));
        districtModels.Add(CreateDistrictModel(793, "Akyazı", 66));
        districtModels.Add(CreateDistrictModel(794, "Arifiye", 66));
        districtModels.Add(CreateDistrictModel(795, "Erenler", 66));
        districtModels.Add(CreateDistrictModel(796, "Ferizli", 66));
        districtModels.Add(CreateDistrictModel(797, "Geyve", 66));
        districtModels.Add(CreateDistrictModel(798, "Hendek", 66));
        districtModels.Add(CreateDistrictModel(799, "Karapürçek", 66));
        districtModels.Add(CreateDistrictModel(800, "Karasu", 66));
        districtModels.Add(CreateDistrictModel(801, "Kaynarca", 66));
        districtModels.Add(CreateDistrictModel(802, "Kocaali", 66));
        districtModels.Add(CreateDistrictModel(803, "Pamukova", 66));
        districtModels.Add(CreateDistrictModel(804, "Sapanca", 66));
        districtModels.Add(CreateDistrictModel(805, "Serdivan", 66));
        districtModels.Add(CreateDistrictModel(806, "Söğütlü", 66));
        districtModels.Add(CreateDistrictModel(807, "Taraklı", 66));
        districtModels.Add(CreateDistrictModel(808, "19 Mayıs", 67));
        districtModels.Add(CreateDistrictModel(809, "Alaçam", 67));
        districtModels.Add(CreateDistrictModel(810, "Asarcık", 67));
        districtModels.Add(CreateDistrictModel(811, "Atakum", 67));
        districtModels.Add(CreateDistrictModel(812, "Ayvacık", 67));
        districtModels.Add(CreateDistrictModel(813, "Bafra", 67));
        districtModels.Add(CreateDistrictModel(814, "Canik", 67));
        districtModels.Add(CreateDistrictModel(815, "Çarşamba", 67));
        districtModels.Add(CreateDistrictModel(816, "Havza", 67));
        districtModels.Add(CreateDistrictModel(817, "İlkadım", 67));
        districtModels.Add(CreateDistrictModel(818, "Kavak", 67));
        districtModels.Add(CreateDistrictModel(819, "Ladik", 67));
        districtModels.Add(CreateDistrictModel(820, "Salıpazarı", 67));
        districtModels.Add(CreateDistrictModel(821, "Tekkeköy", 67));
        districtModels.Add(CreateDistrictModel(822, "Terme", 67));
        districtModels.Add(CreateDistrictModel(823, "Vezirköprü", 67));
        districtModels.Add(CreateDistrictModel(824, "Yakakent", 67));
        districtModels.Add(CreateDistrictModel(825, "Akçakale", 68));
        districtModels.Add(CreateDistrictModel(826, "Birecik", 68));
        districtModels.Add(CreateDistrictModel(827, "Bozova", 68));
        districtModels.Add(CreateDistrictModel(828, "Ceylanpınar", 68));
        districtModels.Add(CreateDistrictModel(829, "Eyyübiye", 68));
        districtModels.Add(CreateDistrictModel(830, "Halfeti", 68));
        districtModels.Add(CreateDistrictModel(831, "Haliliye", 68));
        districtModels.Add(CreateDistrictModel(832, "Harran", 68));
        districtModels.Add(CreateDistrictModel(833, "Hilvan", 68));
        districtModels.Add(CreateDistrictModel(834, "Karaköprü", 68));
        districtModels.Add(CreateDistrictModel(835, "Siverek", 68));
        districtModels.Add(CreateDistrictModel(836, "Suruç", 68));
        districtModels.Add(CreateDistrictModel(837, "Viranşehir", 68));
        districtModels.Add(CreateDistrictModel(838, "Baykan", 69));
        districtModels.Add(CreateDistrictModel(839, "Eruh", 69));
        districtModels.Add(CreateDistrictModel(840, "Kurtalan", 69));
        districtModels.Add(CreateDistrictModel(841, "Merkez", 69));
        districtModels.Add(CreateDistrictModel(842, "Pervari", 69));
        districtModels.Add(CreateDistrictModel(843, "Şirvan", 69));
        districtModels.Add(CreateDistrictModel(844, "Tillo", 69));
        districtModels.Add(CreateDistrictModel(845, "Ayancık", 70));
        districtModels.Add(CreateDistrictModel(846, "Boyabat", 70));
        districtModels.Add(CreateDistrictModel(847, "Dikmen", 70));
        districtModels.Add(CreateDistrictModel(848, "Durağan", 70));
        districtModels.Add(CreateDistrictModel(849, "Erfelek", 70));
        districtModels.Add(CreateDistrictModel(850, "Gerze", 70));
        districtModels.Add(CreateDistrictModel(851, "Merkez", 70));
        districtModels.Add(CreateDistrictModel(852, "Saraydüzü", 70));
        districtModels.Add(CreateDistrictModel(853, "Türkeli", 70));
        districtModels.Add(CreateDistrictModel(854, "Beytüşşebap", 71));
        districtModels.Add(CreateDistrictModel(855, "Cizre", 71));
        districtModels.Add(CreateDistrictModel(856, "Güçlükonak", 71));
        districtModels.Add(CreateDistrictModel(857, "İdil", 71));
        districtModels.Add(CreateDistrictModel(858, "Merkez", 71));
        districtModels.Add(CreateDistrictModel(859, "Silopi", 71));
        districtModels.Add(CreateDistrictModel(860, "Uludere", 71));
        districtModels.Add(CreateDistrictModel(861, "Akıncılar", 72));
        districtModels.Add(CreateDistrictModel(862, "Altınyayla", 72));
        districtModels.Add(CreateDistrictModel(863, "Divriği", 72));
        districtModels.Add(CreateDistrictModel(864, "Doğanşar", 72));
        districtModels.Add(CreateDistrictModel(865, "Gemerek", 72));
        districtModels.Add(CreateDistrictModel(866, "Gölova", 72));
        districtModels.Add(CreateDistrictModel(867, "Gürün", 72));
        districtModels.Add(CreateDistrictModel(868, "Hafik", 72));
        districtModels.Add(CreateDistrictModel(869, "İmranlı", 72));
        districtModels.Add(CreateDistrictModel(870, "Kangal", 72));
        districtModels.Add(CreateDistrictModel(871, "Koyulhisar", 72));
        districtModels.Add(CreateDistrictModel(872, "Merkez", 72));
        districtModels.Add(CreateDistrictModel(873, "Şarkışla", 72));
        districtModels.Add(CreateDistrictModel(874, "Suşehri", 72));
        districtModels.Add(CreateDistrictModel(875, "Ulaş", 72));
        districtModels.Add(CreateDistrictModel(876, "Yıldızeli", 72));
        districtModels.Add(CreateDistrictModel(877, "Zara", 72));
        districtModels.Add(CreateDistrictModel(878, "Çerkezköy", 73));
        districtModels.Add(CreateDistrictModel(879, "Çorlu", 73));
        districtModels.Add(CreateDistrictModel(880, "Ergene", 73));
        districtModels.Add(CreateDistrictModel(881, "Hayrabolu", 73));
        districtModels.Add(CreateDistrictModel(882, "Kapaklı", 73));
        districtModels.Add(CreateDistrictModel(883, "Malkara", 73));
        districtModels.Add(CreateDistrictModel(884, "Marmaraereğlisi", 73));
        districtModels.Add(CreateDistrictModel(885, "Muratlı", 73));
        districtModels.Add(CreateDistrictModel(886, "Saray", 73));
        districtModels.Add(CreateDistrictModel(887, "Şarköy", 73));
        districtModels.Add(CreateDistrictModel(888, "Süleymanpaşa", 73));
        districtModels.Add(CreateDistrictModel(889, "Almus", 74));
        districtModels.Add(CreateDistrictModel(890, "Artova", 74));
        districtModels.Add(CreateDistrictModel(891, "Başçiftlik", 74));
        districtModels.Add(CreateDistrictModel(892, "Erbaa", 74));
        districtModels.Add(CreateDistrictModel(893, "Merkez", 74));
        districtModels.Add(CreateDistrictModel(894, "Niksar", 74));
        districtModels.Add(CreateDistrictModel(895, "Pazar", 74));
        districtModels.Add(CreateDistrictModel(896, "Reşadiye", 74));
        districtModels.Add(CreateDistrictModel(897, "Sulusaray", 74));
        districtModels.Add(CreateDistrictModel(898, "Turhal", 74));
        districtModels.Add(CreateDistrictModel(899, "Yeşilyurt", 74));
        districtModels.Add(CreateDistrictModel(900, "Zile", 74));
        districtModels.Add(CreateDistrictModel(901, "Akçaabat", 75));
        districtModels.Add(CreateDistrictModel(902, "Araklı", 75));
        districtModels.Add(CreateDistrictModel(903, "Arsin", 75));
        districtModels.Add(CreateDistrictModel(904, "Beşikdüzü", 75));
        districtModels.Add(CreateDistrictModel(905, "Çarşıbaşı", 75));
        districtModels.Add(CreateDistrictModel(906, "Çaykara", 75));
        districtModels.Add(CreateDistrictModel(907, "Dernekpazarı", 75));
        districtModels.Add(CreateDistrictModel(908, "Düzköy", 75));
        districtModels.Add(CreateDistrictModel(909, "Hayrat", 75));
        districtModels.Add(CreateDistrictModel(910, "Köprübaşı", 75));
        districtModels.Add(CreateDistrictModel(911, "Maçka", 75));
        districtModels.Add(CreateDistrictModel(912, "Of", 75));
        districtModels.Add(CreateDistrictModel(913, "Ortahisar", 75));
        districtModels.Add(CreateDistrictModel(914, "Şalpazarı", 75));
        districtModels.Add(CreateDistrictModel(915, "Sürmene", 75));
        districtModels.Add(CreateDistrictModel(916, "Tonya", 75));
        districtModels.Add(CreateDistrictModel(917, "Vakfıkebir", 75));
        districtModels.Add(CreateDistrictModel(918, "Yomra", 75));
        districtModels.Add(CreateDistrictModel(919, "Çemişgezek", 76));
        districtModels.Add(CreateDistrictModel(920, "Hozat", 76));
        districtModels.Add(CreateDistrictModel(921, "Mazgirt", 76));
        districtModels.Add(CreateDistrictModel(922, "Merkez", 76));
        districtModels.Add(CreateDistrictModel(923, "Nazımiye", 76));
        districtModels.Add(CreateDistrictModel(924, "Ovacık", 76));
        districtModels.Add(CreateDistrictModel(925, "Pertek", 76));
        districtModels.Add(CreateDistrictModel(926, "Pülümür", 76));
        districtModels.Add(CreateDistrictModel(927, "Banaz", 77));
        districtModels.Add(CreateDistrictModel(928, "Eşme", 77));
        districtModels.Add(CreateDistrictModel(929, "Karahallı", 77));
        districtModels.Add(CreateDistrictModel(930, "Merkez", 77));
        districtModels.Add(CreateDistrictModel(931, "Sivaslı", 77));
        districtModels.Add(CreateDistrictModel(932, "Ulubey", 77));
        districtModels.Add(CreateDistrictModel(933, "Bahçesaray", 78));
        districtModels.Add(CreateDistrictModel(934, "Başkale", 78));
        districtModels.Add(CreateDistrictModel(935, "Çaldıran", 78));
        districtModels.Add(CreateDistrictModel(936, "Çatak", 78));
        districtModels.Add(CreateDistrictModel(937, "Edremit", 78));
        districtModels.Add(CreateDistrictModel(938, "Erciş", 78));
        districtModels.Add(CreateDistrictModel(939, "Gevaş", 78));
        districtModels.Add(CreateDistrictModel(940, "Gürpınar", 78));
        districtModels.Add(CreateDistrictModel(941, "İpekyolu", 78));
        districtModels.Add(CreateDistrictModel(942, "Muradiye", 78));
        districtModels.Add(CreateDistrictModel(943, "Özalp", 78));
        districtModels.Add(CreateDistrictModel(944, "Saray", 78));
        districtModels.Add(CreateDistrictModel(945, "Tuşba", 78));
        districtModels.Add(CreateDistrictModel(946, "Altınova", 79));
        districtModels.Add(CreateDistrictModel(947, "Armutlu", 79));
        districtModels.Add(CreateDistrictModel(948, "Çiftlikköy", 79));
        districtModels.Add(CreateDistrictModel(949, "Çınarcık", 79));
        districtModels.Add(CreateDistrictModel(950, "Merkez", 79));
        districtModels.Add(CreateDistrictModel(951, "Termal", 79));
        districtModels.Add(CreateDistrictModel(952, "Akdağmadeni", 80));
        districtModels.Add(CreateDistrictModel(953, "Aydıncık", 80));
        districtModels.Add(CreateDistrictModel(954, "Boğazlıyan", 80));
        districtModels.Add(CreateDistrictModel(955, "Çandır", 80));
        districtModels.Add(CreateDistrictModel(956, "Çayıralan", 80));
        districtModels.Add(CreateDistrictModel(957, "Çekerek", 80));
        districtModels.Add(CreateDistrictModel(958, "Kadışehri", 80));
        districtModels.Add(CreateDistrictModel(959, "Merkez", 80));
        districtModels.Add(CreateDistrictModel(960, "Saraykent", 80));
        districtModels.Add(CreateDistrictModel(961, "Sarıkaya", 80));
        districtModels.Add(CreateDistrictModel(962, "Şefaatli", 80));
        districtModels.Add(CreateDistrictModel(963, "Sorgun", 80));
        districtModels.Add(CreateDistrictModel(964, "Yenifakılı", 80));
        districtModels.Add(CreateDistrictModel(965, "Yerköy", 80));
        districtModels.Add(CreateDistrictModel(966, "Alaplı", 81));
        districtModels.Add(CreateDistrictModel(967, "Çaycuma", 81));
        districtModels.Add(CreateDistrictModel(968, "Devrek", 81));
        districtModels.Add(CreateDistrictModel(969, "Ereğli", 81));
        districtModels.Add(CreateDistrictModel(970, "Gökçebey", 81));
        districtModels.Add(CreateDistrictModel(971, "Kilimli", 81));
        districtModels.Add(CreateDistrictModel(972, "Kozlu", 81));
        districtModels.Add(CreateDistrictModel(973, "Merkez", 81));
        return districtModels;
    }

    private DistrictModel CreateDistrictModel(int id, string district, int cityId)
    {
        return new DistrictModel
        {
            Id = id,
            Name = district,
            CityId = cityId
        };
    }
    #endregion

    #region CompanyInfo

    public CompanyInfoModel CreateCompanyInfo()
    {
        return new CompanyInfoModel
        {
            Id = 1,
            AboutUs = "Grafitist satış kanalı",
            Address = "Kocamustafapaşa civarı",
            Email = "grafitist@gmail.com",
            Phone = "0 555 555 55 55",
            GoogleMapLink = "map.google.com"
        };
    }

    #endregion

}